
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: auth_services
  config:
    import: optional:configserver:http//localhost:8888
    datasource:
      url: jdbc:mysql://localhost:3306/kamel_db
      username: root
      password: 1234

    jpa:
      hibernate:
        ddl-auto: update

    servlet:
      multipart:
        enabled: true
        max-file-size: 2MB
        max-request-size: 2MB
application:
  config:
    students-url: http://localhost:8081/api/auth
  server:
    port: 8082
management:
  tracing:
    sampling:
      probability: 1.0