spring:
  application:
    name: gateway


  cloud:
    gateway:
      routes:
        ## service1
        - id: articles_services
          uri: lb://articles_services

          predicates:
            - Path=/api/articles**
          filters:
            - StripPrefix=1


server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka