eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: articles_services

  datasource:
    url: jdbc:mysql://localhost:3306/kamel_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

server:
  port: 8081

logging:
  level:
    org:
      springframework: DEBUG
