spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  cloud:
    config:
      import-check:
        enabled: false
